---
- name: elb
  hosts: localhost
  vars_files:
          - variable.yml
  tasks:
          - elb_application_lb_info:
                    region: "{{ project_region }}"
                    names: "{{ project_name }}-nlb"
            register: elb
- name: web
  hosts: _web
  become: true
  vars_files:
          - variable.yml
  tasks:
          - name: httpd
            yum:
                    name: httpd
                    state: latest
          - name: start
            service:
                    name: httpd
                    state: started
                    enabled: true
            ignore_errors: true
          - name: proxy1
            blockinfile:
                    dest: /etc/httpd/conf/httpd.conf
                    content: |
                            ProxyRequests Off
                            ProxyPreserveHost On
                            <Proxy *>
                                    Order deny,allow
                                    Allow from all
                            </Proxy>
                            ProxyPass / http://{{ item }}:8080/
                            ProxyPassReverse / http://{{ item }}:8080/
                    insertbefore: "^</VirtualHost>$"
            with_items: '{{ hostvars["localhost"]["elb"].load_balancers[0].dns_name }}'
          - name: proxy2
            systemd:
                    name: httpd
                    state: restarted
                    enabled: true