---
- name: Install apache and start
  hosts: web
  tasks:
          - name: Install apache
            apt:
                    name: apache2
                    state: present
          - name: block proxy
            blockinfile:
                    path: /etc/httpd/conf/httpd.conf
                    block: |
                      ProxyRequests Off
                          <Proxy *>
                                  Order deny,allow
                                  Allow from all
                          </Proxy>

                          ProxyPass / http://cd-alb-2022114028.ap-northeast-2.elb.amazonaws.com
                          ProxyPassMatch ^/(.*\.do)$ http://cd-nlb-177dd9b57f99be24.elb.ap-northeast-2.amazonaws.com:8080/ 
                          ProxyPassMatch ^/(.*\.jsp)$ http://cd-nlb-177dd9b57f99be24.elb.ap-northeast-2.amazonaws.com:8080/
                          ProxyPassReverse / http://cd-nlb-177dd9b57f99be24.elb.ap-northeast-2.amazonaws.com
                    state: present
          - name: start httpd
            service:
                    name: apache2
                    state: started

          - name: start apache
            service:
                    name: apache2
                    enabled: yes
          - name: restart apache
            service:
                    name: apache2
                    state: restarted