---
- name: bastion
  hosts: _bastion
  become: true
  vars_files:
          - variable.yaml
  vars:
          ansible_ssh_private_key_file: '{{ key_name }}'
  tasks:
          - name: make directory ebs
            file:
                    path: /home/ec2-user/ebs
                    state: directory
          - name: make file system ebs
            filesystem:
                    fstype: xfs
                    dev: /dev/sdh
          - name: mount ebs
            mount:
                    path: /home/ec2-user/ebs
                    src: /dev/sdh
                    state: mounted
                    fstype: xfs
          - name: change owner ebs
            file:
                    dest: /home/ec2-user/ebs
                    owner: ec2-user
                    group: ec2-user
                    state: directory